[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "simplex"
version = "0.0.1"
authors = [
  { name="Sudhendra Kambhamettu", email="sudhendrakambhamettu@gmail.com" },
]
description = "A text pre-processing package"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Sudhendra/Simplex"
